version: '3.4'

services:
  squared-dispatch-deamon:
    build:
      context: ./deamon
      network: host
      args:
        FEDEX_PRINTER_IP: 192.168.1.5
    volumes:
      - type: bind
        source: $HOME/Downloads
        target: /target
