version: "3.9"

services:
  squared-dispatch-deamon:
    build:
      context: ./deamon
      network: host
      args:
        DEFAULT_PRINTER_IP: 192.168.1.202
        FEDEX_PRINTER_IP: 192.168.1.201
    restart: unless-stopped
    volumes:
      - type: bind
        source: C:\Users\{USERNAME}\Downloads
        target: /target
