version: "3.9"

services:
  squared-dispatch-deamon:
    build:
      context: ./deamon
      network: host
      args:
        FEDEX_PRINTER_IP: 192.168.1.201
    volumes:
      - type: bind
        source: $HOME/Stažené
        target: /target
